### ISSUE TITLE
Add support for additional options available in network templates

### ISSUE THREAD

**Issue by hefernan** [CiscoDevNet/ansible-dcnm#33]
Things like enable L3 on border, or any other of the options in the default network and network extension templates

**Comment by hefernan** [comment]
The default network and default network extension templates provide support for additional configuration options.
It would be interesting to be able to add fields that are part the default network template applied.
As a further enhancement, those fields could be matched against any other field added to the actual template applied to the network.

**Comment by gve-vse-tim** [comment]
Would like to raise awareness in implementing this feature request that the "L3 on border" - at least in the DCNM GUI - is only available is Easy Fabric templates and not in Multisite Domain template scoped networks.  You have to select the different fabric scopes in order to enable/disable L3 Gateway on Border.  Don't know how that will be possible given the current behavior of the ansible module.

**Comment by dsx1123** [comment]
some of the attributes is added recently, please refer to PR #74, however l3 on border is not part of it, we can add check if the fabric is MSD or not to return error if L3 on border is set when deploy to MSD.

**Comment by richwats** [comment]
+1 for "Enable L3 Gateway on Border" support.  This is already available in the equivalent Terraform resource.

**Comment by praveenramoorthy** [comment]
Fixed as part of #208
